CREATE TABLE CUSTOMER
(
    id            BIGINT AUTO_INCREMENT,
    uuid          UUID         NOT NULL,
    prename       VARCHAR(255) NULL,
    lastname      VARCHAR(255) NULL,
    date_of_birth DATE         NULL
);
ALTER TABLE CUSTOMER
    ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY (id);
ALTER TABLE CUSTOMER
    ADD CONSTRAINT UQ_CUSTOMER_UUID UNIQUE (uuid);
CREATE UNIQUE INDEX IDX_CUSTOMER_UUID ON CUSTOMER (uuid);

CREATE SEQUENCE ACCOUNT_NUMBER
    START WITH 1
    INCREMENT BY 1
    NOCACHE
    NOCYCLE;

CREATE TABLE ACCOUNT
(
    id          BIGINT       NOT NULL DEFAULT ACCOUNT_NUMBER.nextval,
    uuid        UUID         NOT NULL,
    iban        VARCHAR(255) NOT NULL,
    customer_id BIGINT       NOT NULL
);
ALTER TABLE ACCOUNT
    ADD CONSTRAINT PK_ACCOUNT PRIMARY KEY (id);
ALTER TABLE ACCOUNT
    ADD CONSTRAINT FK_ACCOUNT_ON_CUSTOMER FOREIGN KEY (customer_id)
        REFERENCES CUSTOMER (id) ON DELETE CASCADE;
ALTER TABLE ACCOUNT
    ADD CONSTRAINT UQ_ACCOUNT_UUID UNIQUE (uuid);
CREATE UNIQUE INDEX IDX_ACCOUNT_UUID ON ACCOUNT (uuid);
ALTER TABLE ACCOUNT
    ADD CONSTRAINT UQ_ACCOUNT_IBAN UNIQUE (iban);
CREATE UNIQUE INDEX IDX_ACCOUNT_IBAN ON ACCOUNT (iban);


CREATE TABLE BALANCE
(
    id             BIGINT AUTO_INCREMENT,
    uuid           UUID     NOT NULL,
    value_in_cents DECIMAL  NULL,
    last_update    DATETIME NULL,
    account_id     BIGINT   NOT NULL
);
ALTER TABLE BALANCE
    ADD CONSTRAINT PK_BALANCE PRIMARY KEY (id);
ALTER TABLE BALANCE
    ADD CONSTRAINT UQ_BALANCE_UUID UNIQUE (uuid);
CREATE UNIQUE INDEX IDX_BALANCE_UUID ON BALANCE (uuid);
ALTER TABLE BALANCE
    ADD CONSTRAINT FK_BALANCE_ON_ACCOUNT FOREIGN KEY (account_id)
        REFERENCES ACCOUNT (id) ON DELETE CASCADE;

CREATE TABLE TRANSACTION_STATUS
(
    value VARCHAR(255) NOT NULL
);
ALTER TABLE TRANSACTION_STATUS
    ADD CONSTRAINT PK_TRANSACTION_STATUS PRIMARY KEY (value);

CREATE TABLE TRANSACTION
(
    id               BIGINT AUTO_INCREMENT,
    uuid             UUID         NOT NULL,
    value_in_cents   DECIMAL      NULL,
    status           VARCHAR(255) NULL,
    transaction_time DATETIME     NULL,
    descr            VARCHAR(255) NULL,
    sender_id        BIGINT       NOT NULL,
    receiver_id      BIGINT       NOT NULL
);
ALTER TABLE TRANSACTION
    ADD CONSTRAINT PK_TRANSACTION PRIMARY KEY (id);
ALTER TABLE TRANSACTION
    ADD CONSTRAINT UQ_TRANSACTION_UUID UNIQUE (uuid);
CREATE UNIQUE INDEX IDX_TRANSACTION_UUID ON TRANSACTION (uuid);
ALTER TABLE TRANSACTION
    ADD CONSTRAINT FK_TRANSACTION_ON_RECEIVER FOREIGN KEY (receiver_id)
        REFERENCES ACCOUNT (id) ON DELETE CASCADE;
ALTER TABLE TRANSACTION
    ADD CONSTRAINT FK_TRANSACTION_ON_SENDER FOREIGN KEY (sender_id)
        REFERENCES ACCOUNT (id) ON DELETE CASCADE;
ALTER TABLE TRANSACTION
    ADD CONSTRAINT FK_TRANSACTION_ON_STATUS FOREIGN KEY (status)
        REFERENCES TRANSACTION_STATUS (value) ON DELETE CASCADE;
